/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EnterprisesRouteImport } from './routes/enterprises'
import { Route as IndexRouteImport } from './routes/index'

const EnterprisesRoute = EnterprisesRouteImport.update({
  id: '/enterprises',
  path: '/enterprises',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/enterprises': typeof EnterprisesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/enterprises': typeof EnterprisesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/enterprises': typeof EnterprisesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/enterprises'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/enterprises'
  id: '__root__' | '/' | '/enterprises'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnterprisesRoute: typeof EnterprisesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/enterprises': {
      id: '/enterprises'
      path: '/enterprises'
      fullPath: '/enterprises'
      preLoaderRoute: typeof EnterprisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnterprisesRoute: EnterprisesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
