import { AccessRequirement } from './access-requirement';

export interface AuthorizationRoutePolicy {
  method: string;
  path: string;
  public: boolean;
  access: AccessRequirement | null;
}

export const authorizationRoutePolicies: readonly AuthorizationRoutePolicy[] = [
  { method: 'ALL', path: '/auth/*', public: true, access: null },
  { method: 'DELETE', path: '/extraction-hints/:id', public: false, access: { kind: 'access', module: 'documents', level: 'edit' } },
  { method: 'DELETE', path: '/invoices/:id', public: false, access: { kind: 'access', module: 'invoices', level: 'edit' } },
  { method: 'DELETE', path: '/products/:id', public: false, access: { kind: 'access', module: 'products', level: 'edit' } },
  { method: 'DELETE', path: '/projects/:id', public: false, access: { kind: 'access', module: 'projects', level: 'edit' } },
  { method: 'DELETE', path: '/projects/:projectId/documents/:id', public: false, access: { kind: 'access', module: 'documents', level: 'edit' } },
  { method: 'DELETE', path: '/projects/:projectId/products/:productId', public: false, access: { kind: 'access', module: 'projects', level: 'edit' } },
  { method: 'DELETE', path: '/schedule/events/:id', public: false, access: { kind: 'access', module: 'calendar', level: 'edit' } },
  { method: 'DELETE', path: '/staff/:id', public: false, access: { kind: 'access', module: 'staff', level: 'edit' } },
  { method: 'DELETE', path: '/staff/:staffMemberId/documents/:documentId', public: false, access: { kind: 'access', module: 'staff', level: 'edit' } },
  { method: 'DELETE', path: '/suppliers/:id', public: false, access: { kind: 'access', module: 'suppliers', level: 'edit' } },
  { method: 'DELETE', path: '/workspace/members/:id', public: false, access: { kind: 'admin' } },
  { method: 'GET', path: '/', public: true, access: null },
  { method: 'GET', path: '/auth/me', public: false, access: { kind: 'authenticated' } },
  { method: 'GET', path: '/auth/status', public: true, access: null },
  { method: 'GET', path: '/company', public: false, access: { kind: 'authenticated' } },
  { method: 'GET', path: '/company/branding', public: true, access: { kind: 'authenticated' } },
  { method: 'GET', path: '/dashboard', public: false, access: { kind: 'access', module: 'dashboard', level: 'view' } },
  { method: 'GET', path: '/documents', public: false, access: { kind: 'access', module: 'documents', level: 'view' } },
  { method: 'GET', path: '/documents/duplicate-check', public: false, access: { kind: 'access', module: 'documents', level: 'view' } },
  { method: 'GET', path: '/extraction-hints', public: false, access: { kind: 'access', module: 'documents', level: 'view' } },
  { method: 'GET', path: '/extraction-quality', public: false, access: { kind: 'access', module: 'documents', level: 'view' } },
  { method: 'GET', path: '/health', public: true, access: null },
  { method: 'GET', path: '/health/ready', public: true, access: null },
  { method: 'GET', path: '/invoices', public: false, access: { kind: 'access', module: 'invoices', level: 'view' } },
  { method: 'GET', path: '/invoices/:id', public: false, access: { kind: 'access', module: 'invoices', level: 'view' } },
  { method: 'GET', path: '/invoices/:id/pdf', public: false, access: { kind: 'access', module: 'invoices', level: 'view' } },
  { method: 'GET', path: '/notifications', public: false, access: { kind: 'notifications' } },
  { method: 'GET', path: '/notifications/unread-count', public: false, access: { kind: 'notifications' } },
  { method: 'GET', path: '/products', public: false, access: { kind: 'access', module: 'products', level: 'view' } },
  { method: 'GET', path: '/projects', public: false, access: { kind: 'access', module: 'projects', level: 'view' } },
  { method: 'GET', path: '/projects/:id', public: false, access: { kind: 'access', module: 'projects', level: 'view' } },
  { method: 'GET', path: '/projects/:projectId/documents', public: false, access: { kind: 'access', module: 'documents', level: 'view' } },
  { method: 'GET', path: '/projects/:projectId/documents/:documentId/file', public: false, access: { kind: 'access', module: 'documents', level: 'view' } },
  { method: 'GET', path: '/projects/:projectId/documents/:id', public: false, access: { kind: 'access', module: 'documents', level: 'view' } },
  { method: 'GET', path: '/projects/:projectId/products', public: false, access: { kind: 'access', module: 'projects', level: 'view' } },
  { method: 'GET', path: '/schedule/board', public: false, access: { kind: 'access', module: 'calendar', level: 'view' } },
  { method: 'GET', path: '/schedule/events', public: false, access: { kind: 'access', module: 'calendar', level: 'view' } },
  { method: 'GET', path: '/schedule/schedulable-projects', public: false, access: { kind: 'access', module: 'calendar', level: 'view' } },
  { method: 'GET', path: '/staff', public: false, access: { kind: 'access', module: 'staff', level: 'view' } },
  { method: 'GET', path: '/staff-document-types', public: false, access: { kind: 'access', module: 'staff', level: 'view' } },
  { method: 'GET', path: '/staff/:id', public: false, access: { kind: 'access', module: 'staff', level: 'view' } },
  { method: 'GET', path: '/staff/:staffMemberId/documents', public: false, access: { kind: 'access', module: 'staff', level: 'view' } },
  { method: 'GET', path: '/staff/:staffMemberId/documents/:documentId/file', public: false, access: { kind: 'access', module: 'staff', level: 'view' } },
  { method: 'GET', path: '/suppliers', public: false, access: { kind: 'access', module: 'suppliers', level: 'view' } },
  { method: 'GET', path: '/suppliers/:id', public: false, access: { kind: 'access', module: 'suppliers', level: 'view' } },
  { method: 'GET', path: '/tax-compliance/calendar', public: false, access: { kind: 'access', module: 'calendar', level: 'view' } },
  { method: 'GET', path: '/tax-compliance/catalog', public: false, access: { kind: 'access', module: 'projects', level: 'view' } },
  { method: 'GET', path: '/tax-compliance/profiles', public: false, access: { kind: 'access', module: 'projects', level: 'view' } },
  { method: 'GET', path: '/tax-compliance/profiles/:projectId', public: false, access: { kind: 'access', module: 'projects', level: 'view' } },
  { method: 'GET', path: '/tax-compliance/settings', public: false, access: { kind: 'authenticated' } },
  { method: 'GET', path: '/tax-compliance/sources', public: false, access: { kind: 'admin' } },
  { method: 'GET', path: '/workspace/members', public: false, access: { kind: 'admin' } },
  { method: 'GET', path: '/workspace/members/:id/avatar', public: false, access: { kind: 'admin' } },
  { method: 'PATCH', path: '/company', public: false, access: { kind: 'admin' } },
  { method: 'PATCH', path: '/products/:id', public: false, access: { kind: 'access', module: 'products', level: 'edit' } },
  { method: 'PATCH', path: '/projects/:id', public: false, access: { kind: 'access', module: 'projects', level: 'edit' } },
  { method: 'PATCH', path: '/projects/:projectId/documents/:id', public: false, access: { kind: 'access', module: 'documents', level: 'edit' } },
  { method: 'PATCH', path: '/schedule/events/:id', public: false, access: { kind: 'access', module: 'calendar', level: 'edit' } },
  { method: 'PATCH', path: '/staff/:id', public: false, access: { kind: 'access', module: 'staff', level: 'edit' } },
  { method: 'PATCH', path: '/staff/:staffMemberId/documents/:documentId', public: false, access: { kind: 'access', module: 'staff', level: 'edit' } },
  { method: 'PATCH', path: '/suppliers/:id', public: false, access: { kind: 'access', module: 'suppliers', level: 'edit' } },
  { method: 'PATCH', path: '/tax-compliance/profiles/:projectId', public: false, access: { kind: 'access', module: 'projects', level: 'edit' } },
  { method: 'PATCH', path: '/tax-compliance/settings', public: false, access: { kind: 'admin' } },
  { method: 'PATCH', path: '/tax-compliance/sources/:sourceKey/review', public: false, access: { kind: 'admin' } },
  { method: 'PATCH', path: '/workspace/members/:id', public: false, access: { kind: 'admin' } },
  { method: 'POST', path: '/auth/bootstrap', public: true, access: null },
  { method: 'POST', path: '/demo', public: false, access: { kind: 'admin' } },
  { method: 'POST', path: '/documents/extract', public: false, access: { kind: 'access', module: 'documents', level: 'edit' } },
  { method: 'POST', path: '/invoices', public: false, access: { kind: 'access', module: 'invoices', level: 'edit' } },
  { method: 'POST', path: '/notifications/:id/read', public: false, access: { kind: 'notifications' } },
  { method: 'POST', path: '/notifications/:id/resolve', public: false, access: { kind: 'notifications' } },
  { method: 'POST', path: '/notifications/read-all', public: false, access: { kind: 'notifications' } },
  { method: 'POST', path: '/products', public: false, access: { kind: 'access', module: 'products', level: 'edit' } },
  { method: 'POST', path: '/projects', public: false, access: { kind: 'access', module: 'projects', level: 'edit' } },
  { method: 'POST', path: '/projects/:projectId/documents', public: false, access: { kind: 'access', module: 'documents', level: 'edit' } },
  { method: 'POST', path: '/projects/:projectId/documents/extract', public: false, access: { kind: 'access', module: 'documents', level: 'edit' } },
  { method: 'POST', path: '/projects/:projectId/products', public: false, access: { kind: 'access', module: 'projects', level: 'edit' } },
  { method: 'POST', path: '/schedule/events', public: false, access: { kind: 'access', module: 'calendar', level: 'edit' } },
  { method: 'POST', path: '/staff', public: false, access: { kind: 'access', module: 'staff', level: 'edit' } },
  { method: 'POST', path: '/staff/:staffMemberId/documents', public: false, access: { kind: 'access', module: 'staff', level: 'edit' } },
  { method: 'POST', path: '/suppliers', public: false, access: { kind: 'access', module: 'suppliers', level: 'edit' } },
  { method: 'POST', path: '/tax-compliance/sources/refresh', public: false, access: { kind: 'admin' } },
  { method: 'POST', path: '/workspace/members', public: false, access: { kind: 'admin' } },
];
